---
- name: Install oh-my-zsh and configure ssh
  hosts: all
  gather_facts: yes

  vars:
    src_ssh_config: "templates/shell/ssh-config"
    dst_ssh_config: "~/.ssh/config"

    repositories:
      - { repo: "https://github.com/robbyrussell/oh-my-zsh.git", dest: "{{ ansible_user_dir }}/.oh-my-zsh", version: "master" }

    dotfiles:
      - "templates/shell/.zshrc"
      - "templates/shell/.asdfrc"
      - "templates/shell/.tool-versions"
      - "templates/shell/.default-cargo-crates"
      - "templates/shell/.default-gems"
      - "templates/shell/.default-python-packages"
      - "templates/shell/.gitconfig"

  tasks:
    - name: Ensure destinations exist
      file: path="{{ item.dest }}" state=directory
      loop: "{{ repositories }}"

    - name: Clone repositories
      git: repo="{{ item.repo }}" dest="{{ item.dest }}" version="{{ item.version }}"
      loop: "{{ repositories }}"
      tags:
        - clone

    - name: Install ssh_config
      copy: src="{{ src_ssh_config }}" dest="{{ dst_ssh_config }}" mode=0600
      tags:
        - ssh_config

    - name: Install dotfiles to user directory
      copy: src="{{ item }}" dest="{{ ansible_user_dir }}" mode=0640
      loop: "{{ dotfiles }}"
      tags:
        - dotfiles

    # - name: Set zsh as default shell
    #   user: name={{ ansible_user_id }} shell=/bin/zsh
    # chsh -s /bin/zsh
